import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { CAT_EMO, canAccess } from "../../constants";
import Icon from "./Icon";
const DiscountCard = ({ d, onUse, userPlan }) => {
    const ok = canAccess(userPlan, d.tier);
    const tierColor = { free: "#C9A84C", premium: "#E8C76A", elite: "#C4B5FD" }[d.tier];
    return (_jsxs("div", { className: "dcard", style: { background: "rgba(201,168,76,.025)", border: "1px solid rgba(201,168,76,.1)", borderRadius: 14, padding: 20, cursor: ok ? "pointer" : "default", transition: "all .25s", opacity: ok ? 1 : 0.55 }, onClick: () => ok && onUse && onUse(d), children: [_jsxs("div", { style: { display: "flex", alignItems: "flex-start", justifyContent: "space-between", marginBottom: 12 }, children: [_jsx("div", { style: { width: 42, height: 42, borderRadius: 12, background: "rgba(201,168,76,.07)", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 22, border: "1px solid rgba(201,168,76,.14)" }, children: CAT_EMO[d.category] }), _jsxs("div", { style: { display: "flex", gap: 5, alignItems: "center" }, children: [d.tier !== "free" && (_jsx("span", { className: "badge badge-gold", style: { fontSize: 9 }, children: d.tier === "elite" ? "💎 إليت" : "⭐ بريميوم" })), !ok && _jsx(Icon, { n: "lock", sz: 13, c: "#8B7040" })] })] }), _jsx("div", { style: { fontWeight: 700, fontSize: 14, marginBottom: 4 }, children: d.name }), _jsx("div", { style: { fontSize: 12, color: "#8B7040", marginBottom: 12, lineHeight: 1.6 }, children: d.description }), _jsxs("div", { style: { display: "flex", alignItems: "center", justifyContent: "space-between" }, children: [_jsx("span", { style: { fontSize: 24, fontWeight: 900, color: tierColor }, children: d.percentage }), _jsxs("span", { style: { fontSize: 11, color: "#8B7040", display: "flex", alignItems: "center", gap: 3 }, children: [_jsx(Icon, { n: "pin", sz: 10 }), d.city] })] })] }));
};
export default DiscountCard;
